export interface PointerUpdate {
  link: string;
  description: string;
}

export type StepType =
  | 'click_action'
  | 'select_node'
  | 'set_pointer'
  | 'set_value'
  | 'free_memory'
  | 'traverse';

export interface StepOption {
  label: string;
  value: string;
}

export interface TaskStepDef {
  stepId: string;
  stepNumber: number;
  step_number: number;
  totalStepsInTask: number;
  type: StepType;
  action_type: string;
  title: string;
  prompt: string;
  instruction: string;
  target_field: string;
  c_cpp_code: string;
  cCodeSnippet: string;
  options?: StepOption[];
  correctValue?: string;
  errorHint?: string;
}

export interface HeapNodeDef {
  id?: string;
  address: number;
  data: number;
  prev: number | null;
  next: number | null;
}

export type AtomicActionType =
  | 'create_node'
  | 'set_data'
  | 'set_head'
  | 'set_tail'
  | 'set_next'
  | 'set_prev'
  | 'delete_node'
  | 'select_node'
  | 'traverse_next'
  | 'traverse_prev'
  | 'set_curr'
  | 'set_temp'
  | 'verify';

export interface AtomicStepDef {
  id: string;
  stepNumber: number;
  step_number: number;
  title: string;
  label: string;
  instruction: string;
  description: string;
  action_type: string;
  actionType: AtomicActionType;
  target_field: string;
  targetAddress?: number | null;
  fromAddress?: number;
  targetValue?: number;
  c_cpp_code: string;
  cCodeSnippet: string;
}

export interface TaskSpec {
  id: string;
  task_id: number;
  taskNumber: 1 | 2 | 3;
  task_title: string;
  title: string;
  summary: string;
  total_steps: 6;
  difficulty: '⭐⭐' | '⭐⭐⭐' | '⭐⭐⭐⭐' | '⭐⭐⭐⭐⭐';
  actionType: 'concept' | 'insertion' | 'deletion' | 'traversal';
  initialNodes: number[];
  initialHead: number;
  expectedFinalNodes: number[];
  finalHead: number;
  newCandidateValue?: number;
  targetDeleteValue?: number;
  hint: string;
  successMessage: string;
  pointerUpdates: PointerUpdate[];
  steps: TaskStepDef[];
  // RAM Heap Workspace Specs
  initialHeapNodes: HeapNodeDef[];
  initialHeadAddress: number | null;
  initialTailAddress: number | null;
  newNodeToAllocate?: { address: number; data: number };
  expectedFinalAddresses: number[];
  expectedFinalHeadAddress: number | null;
  expectedFinalTailAddress: number | null;
  atomicSteps: AtomicStepDef[];
}

export interface LevelSpec {
  id: 1 | 2 | 3;
  title: string;
  subtitle: string;
  operation: 'Concepts' | 'Insertion' | 'Deletion';
  badge: string;
  description: string;
  tasks: TaskSpec[];
}

export const GAME_LEVELS: LevelSpec[] = [
  // =========================================================================
  // LEVEL 1: DLL CONCEPTS
  // =========================================================================
  {
    id: 1,
    title: 'LEVEL 1 — DLL Concepts',
    subtitle: 'Understand node structure, assemble a list, and traverse',
    operation: 'Concepts',
    badge: 'Foundations & Traversal',
    description: 'Explore the anatomy of a Doubly Linked List node in memory, link nodes from scratch into a chain, and perform bi-directional pointer traversal.',
    tasks: [
      // -----------------------------------------------------------------------
      // TASK 1: UNDERSTAND A DLL NODE
      // -----------------------------------------------------------------------
      {
        id: 'L1-T1',
        task_id: 1,
        taskNumber: 1,
        title: 'Understand a DLL Node',
        task_title: 'Understand a DLL Node',
        summary: 'Allocate memory for a new node, populate its data payload, set its boundary pointers to NULL, and assign HEAD and TAIL registers.',
        total_steps: 6,
        difficulty: '⭐⭐',
        actionType: 'concept',
        initialNodes: [],
        initialHead: 0,
        expectedFinalNodes: [42],
        finalHead: 42,
        newCandidateValue: 42,
        hint: 'A DLL node contains three key fields: data payload, prev pointer, and next pointer. When initializing the first node, allocate it on the heap, assign data, set both pointers to NULL, and register HEAD and TAIL.',
        successMessage: 'Well done! You mastered the anatomy of a Doubly Linked List node in memory and initialized its boundary registers.',
        pointerUpdates: [
          { link: 'node->data = 42', description: 'Store integer data value 42 in node' },
          { link: 'node->prev = NULL', description: 'No preceding node exists' },
          { link: 'node->next = NULL', description: 'No succeeding node exists' },
          { link: 'HEAD -> 1001', description: 'HEAD register references the only node' },
          { link: 'TAIL -> 1001', description: 'TAIL register references the only node' },
        ],
        steps: [
          {
            stepId: 'l1-t1-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'click_action',
            action_type: 'CLICK_ALLOCATE',
            title: 'Allocate Memory for New Node',
            prompt: 'Allocate Node 1001 on the heap',
            instruction: "Click '+ Allocate Node' in the Pointer Tools bar to allocate dynamic memory on the RAM heap.",
            target_field: 'newNode',
            c_cpp_code: 'Node* newNode = (Node*)malloc(sizeof(Node));',
            cCodeSnippet: 'Node* newNode = (Node*)malloc(sizeof(Node));',
          },
          {
            stepId: 'l1-t1-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'set_value',
            action_type: 'SET_VALUE',
            title: 'Set Node Data Value',
            prompt: 'Assign payload value 42 to node',
            instruction: "Click 'Set Value (42)' or select Node 1001 to store the data payload into newNode->data.",
            target_field: 'newNode->data',
            c_cpp_code: 'newNode->data = 42;',
            cCodeSnippet: 'newNode->data = 42;',
          },
          {
            stepId: 'l1-t1-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Initialize PREV Pointer to NULL',
            prompt: 'Set PREV field of Node 1001 to NULL',
            instruction: "Click the PREV field on Node 1001 and select 'NULL' since this is the first element.",
            target_field: 'newNode->prev',
            c_cpp_code: 'newNode->prev = NULL;',
            cCodeSnippet: 'newNode->prev = NULL;',
          },
          {
            stepId: 'l1-t1-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Initialize NEXT Pointer to NULL',
            prompt: 'Set NEXT field of Node 1001 to NULL',
            instruction: "Click the NEXT field on Node 1001 and select 'NULL' since this is the last element.",
            target_field: 'newNode->next',
            c_cpp_code: 'newNode->next = NULL;',
            cCodeSnippet: 'newNode->next = NULL;',
          },
          {
            stepId: 'l1-t1-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Assign HEAD Register to New Node',
            prompt: 'Direct HEAD to Node 1001',
            instruction: "Select Node 1001 and click the 'HEAD' button (or use the HEAD dropdown) to point HEAD to Node 1001.",
            target_field: 'head',
            c_cpp_code: 'head = newNode;',
            cCodeSnippet: 'head = newNode;',
          },
          {
            stepId: 'l1-t1-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Assign TAIL Register to New Node',
            prompt: 'Direct TAIL to Node 1001',
            instruction: "Select Node 1001 and click the 'TAIL' button (or use the TAIL dropdown) to point TAIL to Node 1001.",
            target_field: 'tail',
            c_cpp_code: 'tail = newNode;',
            cCodeSnippet: 'tail = newNode;',
          },
        ],
        initialHeapNodes: [],
        initialHeadAddress: null,
        initialTailAddress: null,
        newNodeToAllocate: { address: 1001, data: 42 },
        expectedFinalAddresses: [1001],
        expectedFinalHeadAddress: 1001,
        expectedFinalTailAddress: 1001,
        atomicSteps: [
          {
            id: 'l1-t1-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Allocate Memory for New Node',
            label: 'Allocate Memory for New Node (malloc)',
            instruction: "Click '+ Allocate Node' in Pointer Tools to allocate memory at Address 1001.",
            description: 'Allocate memory block on the heap for the new node.',
            action_type: 'CLICK_ALLOCATE',
            actionType: 'create_node',
            target_field: 'newNode',
            targetAddress: 1001,
            c_cpp_code: 'Node* newNode = (Node*)malloc(sizeof(Node));',
            cCodeSnippet: 'Node* newNode = (Node*)malloc(sizeof(Node));',
          },
          {
            id: 'l1-t1-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Set Node Data Value',
            label: 'Assign Data Value: 42',
            instruction: "Set Node 1001 data payload to 42.",
            description: 'Store integer data into the node payload field.',
            action_type: 'SET_VALUE',
            actionType: 'set_data',
            target_field: 'newNode->data',
            targetAddress: 1001,
            targetValue: 42,
            c_cpp_code: 'newNode->data = 42;',
            cCodeSnippet: 'newNode->data = 42;',
          },
          {
            id: 'l1-t1-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Initialize PREV Pointer to NULL',
            label: 'Set PREV = NULL',
            instruction: "Click Node 1001 PREV and select NULL.",
            description: 'Set backward pointer to NULL since there is no previous node.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'newNode->prev',
            fromAddress: 1001,
            targetAddress: null,
            c_cpp_code: 'newNode->prev = NULL;',
            cCodeSnippet: 'newNode->prev = NULL;',
          },
          {
            id: 'l1-t1-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Initialize NEXT Pointer to NULL',
            label: 'Set NEXT = NULL',
            instruction: "Click Node 1001 NEXT and select NULL.",
            description: 'Set forward pointer to NULL since there is no next node.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'newNode->next',
            fromAddress: 1001,
            targetAddress: null,
            c_cpp_code: 'newNode->next = NULL;',
            cCodeSnippet: 'newNode->next = NULL;',
          },
          {
            id: 'l1-t1-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Assign HEAD to New Node',
            label: 'Set HEAD = Node 1001',
            instruction: "Assign HEAD pointer register to Node 1001.",
            description: 'Update HEAD register to point to the new node.',
            action_type: 'SET_POINTER',
            actionType: 'set_head',
            target_field: 'head',
            targetAddress: 1001,
            c_cpp_code: 'head = newNode;',
            cCodeSnippet: 'head = newNode;',
          },
          {
            id: 'l1-t1-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Assign TAIL to New Node',
            label: 'Set TAIL = Node 1001',
            instruction: "Assign TAIL pointer register to Node 1001.",
            description: 'Update TAIL register to point to the new node.',
            action_type: 'SET_POINTER',
            actionType: 'set_tail',
            target_field: 'tail',
            targetAddress: 1001,
            c_cpp_code: 'tail = newNode;',
            cCodeSnippet: 'tail = newNode;',
          },
        ],
      },

      // -----------------------------------------------------------------------
      // TASK 2: BUILD THE DLL
      // -----------------------------------------------------------------------
      {
        id: 'L1-T2',
        task_id: 2,
        taskNumber: 2,
        title: 'Build the DLL',
        task_title: 'Build the DLL',
        summary: 'Wire 3 separate heap nodes into a complete Doubly Linked List by assigning HEAD, establishing bi-directional links, and assigning TAIL.',
        total_steps: 6,
        difficulty: '⭐⭐⭐',
        actionType: 'concept',
        initialNodes: [10, 20, 30],
        initialHead: 0,
        expectedFinalNodes: [10, 20, 30],
        finalHead: 10,
        hint: 'In a Doubly Linked List, for every forward pointer (A->next = B), there must be a reciprocal backward pointer (B->prev = A). Set HEAD to 1001, link 1001 <-> 1002, link 1002 <-> 1003, and set TAIL to 1003.',
        successMessage: 'Superb! You wired multiple independent nodes into a seamless bi-directional Doubly Linked List.',
        pointerUpdates: [
          { link: 'HEAD -> 1001', description: 'Designate Node 1001 as start of list' },
          { link: '1001.next -> 1002', description: 'Forward pointer to Node 1002' },
          { link: '1002.prev -> 1001', description: 'Backward pointer to Node 1001' },
          { link: '1002.next -> 1003', description: 'Forward pointer to Node 1003' },
          { link: '1003.prev -> 1002', description: 'Backward pointer to Node 1002' },
          { link: 'TAIL -> 1003', description: 'Designate Node 1003 as end of list' },
        ],
        steps: [
          {
            stepId: 'l1-t2-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Assign HEAD to First Node (1001)',
            prompt: 'Point HEAD to Node 1001',
            instruction: "Select Node 1001 and click 'HEAD' (or use the HEAD dropdown) to designate the start of the list.",
            target_field: 'head',
            c_cpp_code: 'head = node1; // Node 1001',
            cCodeSnippet: 'head = node1;',
          },
          {
            stepId: 'l1-t2-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link Node 1001 NEXT to Node 1002',
            prompt: 'Set 1001.next to Node 1002',
            instruction: "Click 'NEXT' on Node 1001 and select Node 1002 to create the forward link.",
            target_field: 'node1->next',
            c_cpp_code: 'node1->next = node2;',
            cCodeSnippet: 'node1->next = node2;',
          },
          {
            stepId: 'l1-t2-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link Node 1002 PREV to Node 1001',
            prompt: 'Set 1002.prev to Node 1001',
            instruction: "Click 'PREV' on Node 1002 and select Node 1001 to create the reciprocal backward link.",
            target_field: 'node2->prev',
            c_cpp_code: 'node2->prev = node1;',
            cCodeSnippet: 'node2->prev = node1;',
          },
          {
            stepId: 'l1-t2-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link Node 1002 NEXT to Node 1003',
            prompt: 'Set 1002.next to Node 1003',
            instruction: "Click 'NEXT' on Node 1002 and select Node 1003 to link to the final element.",
            target_field: 'node2->next',
            c_cpp_code: 'node2->next = node3;',
            cCodeSnippet: 'node2->next = node3;',
          },
          {
            stepId: 'l1-t2-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link Node 1003 PREV to Node 1002',
            prompt: 'Set 1003.prev to Node 1002',
            instruction: "Click 'PREV' on Node 1003 and select Node 1002 to create the reciprocal backward link.",
            target_field: 'node3->prev',
            c_cpp_code: 'node3->prev = node2;',
            cCodeSnippet: 'node3->prev = node2;',
          },
          {
            stepId: 'l1-t2-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Assign TAIL to Last Node (1003)',
            prompt: 'Point TAIL to Node 1003',
            instruction: "Select Node 1003 and click 'TAIL' (or use the TAIL dropdown) to mark the end of the list.",
            target_field: 'tail',
            c_cpp_code: 'tail = node3; // Node 1003',
            cCodeSnippet: 'tail = node3;',
          },
        ],
        initialHeapNodes: [
          { address: 1001, data: 10, prev: null, next: null },
          { address: 1002, data: 20, prev: null, next: null },
          { address: 1003, data: 30, prev: null, next: null },
        ],
        initialHeadAddress: null,
        initialTailAddress: null,
        expectedFinalAddresses: [1001, 1002, 1003],
        expectedFinalHeadAddress: 1001,
        expectedFinalTailAddress: 1003,
        atomicSteps: [
          {
            id: 'l1-t2-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Assign HEAD to Node 1001',
            label: 'Assign HEAD = Node 1001',
            instruction: "Set HEAD register to point to Node 1001.",
            description: 'Initialize HEAD pointer to reference the first node.',
            action_type: 'SET_POINTER',
            actionType: 'set_head',
            target_field: 'head',
            targetAddress: 1001,
            c_cpp_code: 'head = node1;',
            cCodeSnippet: 'head = node1;',
          },
          {
            id: 'l1-t2-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Link Node 1001 NEXT to Node 1002',
            label: '1001.next = 1002',
            instruction: "Set Node 1001 NEXT pointer to Node 1002.",
            description: 'Link Node 1001 forward to Node 1002.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'node1->next',
            fromAddress: 1001,
            targetAddress: 1002,
            c_cpp_code: 'node1->next = node2;',
            cCodeSnippet: 'node1->next = node2;',
          },
          {
            id: 'l1-t2-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Link Node 1002 PREV to Node 1001',
            label: '1002.prev = 1001',
            instruction: "Set Node 1002 PREV pointer to Node 1001.",
            description: 'Establish backward link from Node 1002 to Node 1001.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'node2->prev',
            fromAddress: 1002,
            targetAddress: 1001,
            c_cpp_code: 'node2->prev = node1;',
            cCodeSnippet: 'node2->prev = node1;',
          },
          {
            id: 'l1-t2-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Link Node 1002 NEXT to Node 1003',
            label: '1002.next = 1003',
            instruction: "Set Node 1002 NEXT pointer to Node 1003.",
            description: 'Link Node 1002 forward to Node 1003.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'node2->next',
            fromAddress: 1002,
            targetAddress: 1003,
            c_cpp_code: 'node2->next = node3;',
            cCodeSnippet: 'node2->next = node3;',
          },
          {
            id: 'l1-t2-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Link Node 1003 PREV to Node 1002',
            label: '1003.prev = 1002',
            instruction: "Set Node 1003 PREV pointer to Node 1002.",
            description: 'Establish backward link from Node 1003 to Node 1002.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'node3->prev',
            fromAddress: 1003,
            targetAddress: 1002,
            c_cpp_code: 'node3->prev = node2;',
            cCodeSnippet: 'node3->prev = node2;',
          },
          {
            id: 'l1-t2-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Assign TAIL to Node 1003',
            label: 'Assign TAIL = Node 1003',
            instruction: "Set TAIL register to point to Node 1003.",
            description: 'Update TAIL register to designate the list boundary.',
            action_type: 'SET_POINTER',
            actionType: 'set_tail',
            target_field: 'tail',
            targetAddress: 1003,
            c_cpp_code: 'tail = node3;',
            cCodeSnippet: 'tail = node3;',
          },
        ],
      },

      // -----------------------------------------------------------------------
      // TASK 3: TRAVERSE THE DLL
      // -----------------------------------------------------------------------
      {
        id: 'L1-T3',
        task_id: 3,
        taskNumber: 3,
        title: 'Traverse the DLL',
        task_title: 'Traverse the DLL',
        summary: 'Step through the Doubly Linked List forward from HEAD to TAIL, and backward from TAIL to HEAD using a pointer variable curr.',
        total_steps: 6,
        difficulty: '⭐⭐⭐',
        actionType: 'traversal',
        initialNodes: [10, 20, 30],
        initialHead: 10,
        expectedFinalNodes: [10, 20, 30],
        finalHead: 10,
        hint: 'Doubly Linked Lists support two-way traversal. Advance forward with curr = curr->next until curr->next is NULL, then step backward with curr = curr->prev until reaching HEAD.',
        successMessage: 'Great job! You executed complete forward and backward traversal across the Doubly Linked List.',
        pointerUpdates: [
          { link: 'curr = head', description: 'Initialize traversal at start (Node 1001)' },
          { link: 'curr = curr->next', description: 'Advance forward to Node 1002' },
          { link: 'curr = curr->next', description: 'Advance forward to Node 1003 (TAIL)' },
          { link: 'curr->next == NULL', description: 'Confirm end of forward chain' },
          { link: 'curr = curr->prev', description: 'Step backward to Node 1002' },
          { link: 'curr = curr->prev', description: 'Step backward to HEAD (Node 1001)' },
        ],
        steps: [
          {
            stepId: 'l1-t3-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Initialize CURR Pointer at HEAD',
            prompt: 'Point curr to head (Node 1001)',
            instruction: "Select Node 1001 to begin traversal at the start of the list (curr = head).",
            target_field: 'curr',
            c_cpp_code: 'Node* curr = head; // Node 1001',
            cCodeSnippet: 'Node* curr = head;',
          },
          {
            stepId: 'l1-t3-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'traverse',
            action_type: 'TRAVERSE',
            title: 'Traverse Forward to Node 1002',
            prompt: 'curr = curr->next',
            instruction: "Select Node 1002 to advance forward (curr = curr->next).",
            target_field: 'curr',
            c_cpp_code: 'curr = curr->next; // Now at Node 1002 (value: 20)',
            cCodeSnippet: 'curr = curr->next;',
          },
          {
            stepId: 'l1-t3-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'traverse',
            action_type: 'TRAVERSE',
            title: 'Traverse Forward to TAIL (Node 1003)',
            prompt: 'curr = curr->next',
            instruction: "Select Node 1003 (TAIL) to advance to the end of the chain.",
            target_field: 'curr',
            c_cpp_code: 'curr = curr->next; // Now at Node 1003 (value: 30)',
            cCodeSnippet: 'curr = curr->next;',
          },
          {
            stepId: 'l1-t3-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'click_action',
            action_type: 'VERIFY',
            title: 'Verify End of List (curr->next == NULL)',
            prompt: 'Check boundary condition at tail',
            instruction: "Select Node 1003 to confirm tail->next terminates at NULL.",
            target_field: 'curr->next',
            c_cpp_code: 'assert(curr->next == NULL); // End of list verified',
            cCodeSnippet: 'if (curr->next == NULL) { /* Reached tail */ }',
          },
          {
            stepId: 'l1-t3-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'traverse',
            action_type: 'TRAVERSE',
            title: 'Reverse Traverse to Node 1002',
            prompt: 'curr = curr->prev',
            instruction: "Select Node 1002 to trace backward along PREV link (curr = curr->prev).",
            target_field: 'curr',
            c_cpp_code: 'curr = curr->prev; // Backward to Node 1002',
            cCodeSnippet: 'curr = curr->prev;',
          },
          {
            stepId: 'l1-t3-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'traverse',
            action_type: 'TRAVERSE',
            title: 'Reverse Traverse to HEAD (Node 1001)',
            prompt: 'curr = curr->prev',
            instruction: "Select Node 1001 to return to HEAD in reverse (curr = curr->prev).",
            target_field: 'curr',
            c_cpp_code: 'curr = curr->prev; // Returned to HEAD Node 1001',
            cCodeSnippet: 'curr = curr->prev;',
          },
        ],
        initialHeapNodes: [
          { address: 1001, data: 10, prev: null, next: 1002 },
          { address: 1002, data: 20, prev: 1001, next: 1003 },
          { address: 1003, data: 30, prev: 1002, next: null },
        ],
        initialHeadAddress: 1001,
        initialTailAddress: 1003,
        expectedFinalAddresses: [1001, 1002, 1003],
        expectedFinalHeadAddress: 1001,
        expectedFinalTailAddress: 1003,
        atomicSteps: [
          {
            id: 'l1-t3-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Initialize CURR at HEAD',
            label: 'Set CURR = HEAD (1001)',
            instruction: "Set traversal pointer curr to HEAD.",
            description: 'Point curr to head Node 1001.',
            action_type: 'SET_POINTER',
            actionType: 'set_curr',
            target_field: 'curr',
            targetAddress: 1001,
            c_cpp_code: 'Node* curr = head;',
            cCodeSnippet: 'Node* curr = head;',
          },
          {
            id: 'l1-t3-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Traverse Forward to Node 1002',
            label: 'curr = curr->next (1002)',
            instruction: "Advance curr forward to Node 1002.",
            description: 'Move curr pointer forward by one node.',
            action_type: 'TRAVERSE',
            actionType: 'traverse_next',
            target_field: 'curr',
            targetAddress: 1002,
            c_cpp_code: 'curr = curr->next;',
            cCodeSnippet: 'curr = curr->next;',
          },
          {
            id: 'l1-t3-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Traverse Forward to TAIL (1003)',
            label: 'curr = curr->next (1003)',
            instruction: "Advance curr forward to Node 1003.",
            description: 'Move curr pointer forward to tail node.',
            action_type: 'TRAVERSE',
            actionType: 'traverse_next',
            target_field: 'curr',
            targetAddress: 1003,
            c_cpp_code: 'curr = curr->next;',
            cCodeSnippet: 'curr = curr->next;',
          },
          {
            id: 'l1-t3-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Verify Boundary (NULL)',
            label: 'Verify curr->next == NULL',
            instruction: "Confirm that curr->next is NULL at tail.",
            description: 'Verify boundary condition at end of list.',
            action_type: 'VERIFY',
            actionType: 'verify',
            target_field: 'curr->next',
            c_cpp_code: 'assert(curr->next == NULL);',
            cCodeSnippet: 'assert(curr->next == NULL);',
          },
          {
            id: 'l1-t3-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Reverse Traverse to Node 1002',
            label: 'curr = curr->prev (1002)',
            instruction: "Move curr backward to Node 1002.",
            description: 'Step curr pointer backward using PREV.',
            action_type: 'TRAVERSE',
            actionType: 'traverse_prev',
            target_field: 'curr',
            targetAddress: 1002,
            c_cpp_code: 'curr = curr->prev;',
            cCodeSnippet: 'curr = curr->prev;',
          },
          {
            id: 'l1-t3-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Reverse Traverse to HEAD (1001)',
            label: 'curr = curr->prev (1001)',
            instruction: "Move curr backward to return to HEAD Node 1001.",
            description: 'Step curr pointer backward to reach HEAD.',
            action_type: 'TRAVERSE',
            actionType: 'traverse_prev',
            target_field: 'curr',
            targetAddress: 1001,
            c_cpp_code: 'curr = curr->prev;',
            cCodeSnippet: 'curr = curr->prev;',
          },
        ],
      },
    ],
  },

  // =========================================================================
  // LEVEL 2: INSERTION
  // =========================================================================
  {
    id: 2,
    title: 'LEVEL 2 — Insertion',
    subtitle: 'Prepend, append, and insert at arbitrary positions',
    operation: 'Insertion',
    badge: 'O(1) & O(N) Pointer Insertion',
    description: 'Master granular pointer assignment for all 3 insertion archetypes: insert at beginning, insert at end, and insert at an arbitrary middle position.',
    tasks: [
      // -----------------------------------------------------------------------
      // TASK 1: INSERT AT BEGINNING
      // -----------------------------------------------------------------------
      {
        id: 'L2-T1',
        task_id: 1,
        taskNumber: 1,
        title: 'Insert at Beginning',
        task_title: 'Insert at Beginning',
        summary: 'Allocate a new node, set its data and boundary pointers, wire it before the existing HEAD, and update the HEAD register.',
        total_steps: 6,
        difficulty: '⭐⭐⭐',
        actionType: 'insertion',
        initialNodes: [10, 20],
        initialHead: 10,
        expectedFinalNodes: [5, 10, 20],
        finalHead: 5,
        newCandidateValue: 5,
        hint: 'To insert at the beginning: allocate the node, set data = 5, set newNode->prev = NULL, link newNode->next = head, link head->prev = newNode, and update head = newNode.',
        successMessage: 'Excellent! You prepended a node to the beginning of the Doubly Linked List with reciprocal pointer synchronization.',
        pointerUpdates: [
          { link: 'newNode->data = 5', description: 'Store value 5 in new head node' },
          { link: 'newNode->prev = NULL', description: 'New head has no predecessor' },
          { link: 'newNode->next = head', description: 'Link new node forward to old head (1001)' },
          { link: 'head->prev = newNode', description: 'Link old head backward to new node (1000)' },
          { link: 'head = newNode', description: 'Update HEAD register to point to 1000' },
        ],
        steps: [
          {
            stepId: 'l2-t1-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'click_action',
            action_type: 'CLICK_ALLOCATE',
            title: 'Allocate Memory for New Head Node',
            prompt: 'Allocate Node 1000 on heap',
            instruction: "Click '+ Allocate Node [5]' in Pointer Tools to allocate memory at Address 1000.",
            target_field: 'newNode',
            c_cpp_code: 'Node* newNode = (Node*)malloc(sizeof(Node));',
            cCodeSnippet: 'Node* newNode = (Node*)malloc(sizeof(Node));',
          },
          {
            stepId: 'l2-t1-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'set_value',
            action_type: 'SET_VALUE',
            title: 'Set Node Data Value',
            prompt: 'Assign payload 5',
            instruction: "Set newNode->data = 5 in the newly allocated node.",
            target_field: 'newNode->data',
            c_cpp_code: 'newNode->data = 5;',
            cCodeSnippet: 'newNode->data = 5;',
          },
          {
            stepId: 'l2-t1-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Initialize PREV Pointer to NULL',
            prompt: 'newNode->prev = NULL',
            instruction: "Click 'PREV' on Node 1000 and select 'NULL' since it will be the new start.",
            target_field: 'newNode->prev',
            c_cpp_code: 'newNode->prev = NULL;',
            cCodeSnippet: 'newNode->prev = NULL;',
          },
          {
            stepId: 'l2-t1-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link New Node NEXT to Current HEAD',
            prompt: 'newNode->next = head (1001)',
            instruction: "Click 'NEXT' on Node 1000 and select Node 1001 to link to the existing list.",
            target_field: 'newNode->next',
            c_cpp_code: 'newNode->next = head; // Node 1001',
            cCodeSnippet: 'newNode->next = head;',
          },
          {
            stepId: 'l2-t1-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link Current HEAD PREV to New Node',
            prompt: 'head->prev = newNode (1000)',
            instruction: "Click 'PREV' on Node 1001 and select Node 1000 to complete reciprocal link.",
            target_field: 'head->prev',
            c_cpp_code: 'head->prev = newNode; // Node 1000',
            cCodeSnippet: 'head->prev = newNode;',
          },
          {
            stepId: 'l2-t1-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Reassign HEAD Register to New Node',
            prompt: 'head = newNode (1000)',
            instruction: "Select Node 1000 and click 'HEAD' (or select 1000 in HEAD register) to advance HEAD.",
            target_field: 'head',
            c_cpp_code: 'head = newNode;',
            cCodeSnippet: 'head = newNode;',
          },
        ],
        initialHeapNodes: [
          { address: 1001, data: 10, prev: null, next: 1002 },
          { address: 1002, data: 20, prev: 1001, next: null },
        ],
        initialHeadAddress: 1001,
        initialTailAddress: 1002,
        newNodeToAllocate: { address: 1000, data: 5 },
        expectedFinalAddresses: [1000, 1001, 1002],
        expectedFinalHeadAddress: 1000,
        expectedFinalTailAddress: 1002,
        atomicSteps: [
          {
            id: 'l2-t1-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Allocate Memory for New Head Node',
            label: 'Allocate Node 1000',
            instruction: "Click '+ Allocate Node [5]' to create Node 1000 in RAM.",
            description: 'Allocate memory block on the heap.',
            action_type: 'CLICK_ALLOCATE',
            actionType: 'create_node',
            target_field: 'newNode',
            targetAddress: 1000,
            c_cpp_code: 'Node* newNode = (Node*)malloc(sizeof(Node));',
            cCodeSnippet: 'Node* newNode = (Node*)malloc(sizeof(Node));',
          },
          {
            id: 'l2-t1-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Set Node Data Value',
            label: 'newNode->data = 5',
            instruction: "Assign value 5 to Node 1000.",
            description: 'Store value 5 into data payload.',
            action_type: 'SET_VALUE',
            actionType: 'set_data',
            target_field: 'newNode->data',
            targetAddress: 1000,
            targetValue: 5,
            c_cpp_code: 'newNode->data = 5;',
            cCodeSnippet: 'newNode->data = 5;',
          },
          {
            id: 'l2-t1-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Initialize PREV to NULL',
            label: 'newNode->prev = NULL',
            instruction: "Set Node 1000 PREV to NULL.",
            description: 'Initialize backward pointer to NULL.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'newNode->prev',
            fromAddress: 1000,
            targetAddress: null,
            c_cpp_code: 'newNode->prev = NULL;',
            cCodeSnippet: 'newNode->prev = NULL;',
          },
          {
            id: 'l2-t1-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Link New Node NEXT to HEAD',
            label: '1000.next = 1001',
            instruction: "Set Node 1000 NEXT pointer to Node 1001.",
            description: 'Link new node forward to current head.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'newNode->next',
            fromAddress: 1000,
            targetAddress: 1001,
            c_cpp_code: 'newNode->next = head;',
            cCodeSnippet: 'newNode->next = head;',
          },
          {
            id: 'l2-t1-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Link Current HEAD PREV to New Node',
            label: '1001.prev = 1000',
            instruction: "Set Node 1001 PREV pointer to Node 1000.",
            description: 'Link existing head backward to new node.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'head->prev',
            fromAddress: 1001,
            targetAddress: 1000,
            c_cpp_code: 'head->prev = newNode;',
            cCodeSnippet: 'head->prev = newNode;',
          },
          {
            id: 'l2-t1-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Reassign HEAD to New Node',
            label: 'HEAD = Node 1000',
            instruction: "Update HEAD register to point to Node 1000.",
            description: 'Reassign HEAD register to the newly prepended node.',
            action_type: 'SET_POINTER',
            actionType: 'set_head',
            target_field: 'head',
            targetAddress: 1000,
            c_cpp_code: 'head = newNode;',
            cCodeSnippet: 'head = newNode;',
          },
        ],
      },

      // -----------------------------------------------------------------------
      // TASK 2: INSERT AT END
      // -----------------------------------------------------------------------
      {
        id: 'L2-T2',
        task_id: 2,
        taskNumber: 2,
        title: 'Insert at End',
        task_title: 'Insert at End',
        summary: 'Allocate a new node, initialize its terminator NEXT pointer to NULL, link it bi-directionally with the existing tail, and advance the TAIL register.',
        total_steps: 6,
        difficulty: '⭐⭐⭐',
        actionType: 'insertion',
        initialNodes: [10, 20],
        initialHead: 10,
        expectedFinalNodes: [10, 20, 30],
        finalHead: 10,
        newCandidateValue: 30,
        hint: 'To append to the end: allocate Node 1003, set data = 30, set newNode->next = NULL, link newNode->prev = tail, link tail->next = newNode, and update tail = newNode.',
        successMessage: 'Great job! You appended a node to the tail of the Doubly Linked List in O(1) time.',
        pointerUpdates: [
          { link: 'newNode->data = 30', description: 'Store value 30 in new tail node' },
          { link: 'newNode->next = NULL', description: 'New tail terminates forward list' },
          { link: 'newNode->prev = tail', description: 'Link new node backward to old tail (1002)' },
          { link: 'tail->next = newNode', description: 'Link old tail forward to new node (1003)' },
          { link: 'tail = newNode', description: 'Update TAIL register to point to 1003' },
        ],
        steps: [
          {
            stepId: 'l2-t2-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'click_action',
            action_type: 'CLICK_ALLOCATE',
            title: 'Allocate Memory for New Tail Node',
            prompt: 'Allocate Node 1003 on heap',
            instruction: "Click '+ Allocate Node [30]' to allocate memory at Address 1003 in heap RAM.",
            target_field: 'newNode',
            c_cpp_code: 'Node* newNode = (Node*)malloc(sizeof(Node));',
            cCodeSnippet: 'Node* newNode = (Node*)malloc(sizeof(Node));',
          },
          {
            stepId: 'l2-t2-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'set_value',
            action_type: 'SET_VALUE',
            title: 'Set Node Data Value',
            prompt: 'Assign payload 30',
            instruction: "Set newNode->data = 30 in the allocated node.",
            target_field: 'newNode->data',
            c_cpp_code: 'newNode->data = 30;',
            cCodeSnippet: 'newNode->data = 30;',
          },
          {
            stepId: 'l2-t2-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Initialize NEXT Pointer to NULL',
            prompt: 'newNode->next = NULL',
            instruction: "Click 'NEXT' on Node 1003 and select 'NULL' since this node will terminate the list.",
            target_field: 'newNode->next',
            c_cpp_code: 'newNode->next = NULL;',
            cCodeSnippet: 'newNode->next = NULL;',
          },
          {
            stepId: 'l2-t2-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link New Node PREV to Current TAIL',
            prompt: 'newNode->prev = tail (1002)',
            instruction: "Click 'PREV' on Node 1003 and select Node 1002 to link backward to the old tail.",
            target_field: 'newNode->prev',
            c_cpp_code: 'newNode->prev = tail; // Node 1002',
            cCodeSnippet: 'newNode->prev = tail;',
          },
          {
            stepId: 'l2-t2-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link Current TAIL NEXT to New Node',
            prompt: 'tail->next = newNode (1003)',
            instruction: "Click 'NEXT' on Node 1002 and select Node 1003 to link forward to the new node.",
            target_field: 'tail->next',
            c_cpp_code: 'tail->next = newNode; // Node 1003',
            cCodeSnippet: 'tail->next = newNode;',
          },
          {
            stepId: 'l2-t2-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Advance TAIL Register to New Node',
            prompt: 'tail = newNode (1003)',
            instruction: "Select Node 1003 and click 'TAIL' (or select 1003 in TAIL register) to advance TAIL.",
            target_field: 'tail',
            c_cpp_code: 'tail = newNode;',
            cCodeSnippet: 'tail = newNode;',
          },
        ],
        initialHeapNodes: [
          { address: 1001, data: 10, prev: null, next: 1002 },
          { address: 1002, data: 20, prev: 1001, next: null },
        ],
        initialHeadAddress: 1001,
        initialTailAddress: 1002,
        newNodeToAllocate: { address: 1003, data: 30 },
        expectedFinalAddresses: [1001, 1002, 1003],
        expectedFinalHeadAddress: 1001,
        expectedFinalTailAddress: 1003,
        atomicSteps: [
          {
            id: 'l2-t2-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Allocate Memory for New Tail Node',
            label: 'Allocate Node 1003',
            instruction: "Click '+ Allocate Node [30]' to allocate memory in RAM.",
            description: 'Allocate node on the heap.',
            action_type: 'CLICK_ALLOCATE',
            actionType: 'create_node',
            target_field: 'newNode',
            targetAddress: 1003,
            c_cpp_code: 'Node* newNode = (Node*)malloc(sizeof(Node));',
            cCodeSnippet: 'Node* newNode = (Node*)malloc(sizeof(Node));',
          },
          {
            id: 'l2-t2-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Set Node Data Value',
            label: 'newNode->data = 30',
            instruction: "Set Node 1003 data payload to 30.",
            description: 'Store integer data in payload.',
            action_type: 'SET_VALUE',
            actionType: 'set_data',
            target_field: 'newNode->data',
            targetAddress: 1003,
            targetValue: 30,
            c_cpp_code: 'newNode->data = 30;',
            cCodeSnippet: 'newNode->data = 30;',
          },
          {
            id: 'l2-t2-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Initialize NEXT to NULL',
            label: 'newNode->next = NULL',
            instruction: "Set Node 1003 NEXT to NULL.",
            description: 'Terminate forward list with NULL.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'newNode->next',
            fromAddress: 1003,
            targetAddress: null,
            c_cpp_code: 'newNode->next = NULL;',
            cCodeSnippet: 'newNode->next = NULL;',
          },
          {
            id: 'l2-t2-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Link New Node PREV to TAIL',
            label: '1003.prev = 1002',
            instruction: "Set Node 1003 PREV pointer to Node 1002.",
            description: 'Link backward to existing tail.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'newNode->prev',
            fromAddress: 1003,
            targetAddress: 1002,
            c_cpp_code: 'newNode->prev = tail;',
            cCodeSnippet: 'newNode->prev = tail;',
          },
          {
            id: 'l2-t2-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Link Current TAIL NEXT to New Node',
            label: '1002.next = 1003',
            instruction: "Set Node 1002 NEXT pointer to Node 1003.",
            description: 'Link old tail forward to new node.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'tail->next',
            fromAddress: 1002,
            targetAddress: 1003,
            c_cpp_code: 'tail->next = newNode;',
            cCodeSnippet: 'tail->next = newNode;',
          },
          {
            id: 'l2-t2-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Advance TAIL to New Node',
            label: 'TAIL = Node 1003',
            instruction: "Update TAIL register to point to Node 1003.",
            description: 'Reassign TAIL register to the new end of list.',
            action_type: 'SET_POINTER',
            actionType: 'set_tail',
            target_field: 'tail',
            targetAddress: 1003,
            c_cpp_code: 'tail = newNode;',
            cCodeSnippet: 'tail = newNode;',
          },
        ],
      },

      // -----------------------------------------------------------------------
      // TASK 3: INSERT AT ANY POSITION
      // -----------------------------------------------------------------------
      {
        id: 'L2-T3',
        task_id: 3,
        taskNumber: 3,
        title: 'Insert at Any Position',
        task_title: 'Insert at Any Position',
        summary: 'Insert an intermediate node between two existing nodes by wiring 4 pointers in careful order to prevent losing chain references.',
        total_steps: 6,
        difficulty: '⭐⭐⭐⭐',
        actionType: 'insertion',
        initialNodes: [10, 30],
        initialHead: 10,
        expectedFinalNodes: [10, 20, 30],
        finalHead: 10,
        newCandidateValue: 20,
        hint: 'When inserting in the middle: 1) allocate node, 2) set data = 20, 3) link newNode->next to successor (1003), 4) link newNode->prev to predecessor (1001), 5) link successor->prev to newNode, and 6) link predecessor->next to newNode.',
        successMessage: 'Masterful! You inserted a node into the middle of a Doubly Linked List without breaking existing pointers.',
        pointerUpdates: [
          { link: 'newNode->data = 20', description: 'Store value 20 in middle node' },
          { link: 'newNode->next = curr->next', description: 'Link new node forward to successor Node 1003' },
          { link: 'newNode->prev = curr', description: 'Link new node backward to predecessor Node 1001' },
          { link: 'curr->next->prev = newNode', description: 'Link successor Node 1003 backward to newNode' },
          { link: 'curr->next = newNode', description: 'Link predecessor Node 1001 forward to newNode' },
        ],
        steps: [
          {
            stepId: 'l2-t3-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'click_action',
            action_type: 'CLICK_ALLOCATE',
            title: 'Allocate Memory for Intermediate Node',
            prompt: 'Allocate Node 1002 on heap',
            instruction: "Click '+ Allocate Node [20]' in Pointer Tools to allocate memory at Address 1002.",
            target_field: 'newNode',
            c_cpp_code: 'Node* newNode = (Node*)malloc(sizeof(Node));',
            cCodeSnippet: 'Node* newNode = (Node*)malloc(sizeof(Node));',
          },
          {
            stepId: 'l2-t3-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'set_value',
            action_type: 'SET_VALUE',
            title: 'Set Node Data Value',
            prompt: 'Assign payload 20',
            instruction: "Set newNode->data = 20 in the allocated node.",
            target_field: 'newNode->data',
            c_cpp_code: 'newNode->data = 20;',
            cCodeSnippet: 'newNode->data = 20;',
          },
          {
            stepId: 'l2-t3-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link New Node NEXT to Successor (Node 1003)',
            prompt: 'newNode->next = 1003',
            instruction: "Click 'NEXT' on Node 1002 and select Node 1003 to link forward to the successor.",
            target_field: 'newNode->next',
            c_cpp_code: 'newNode->next = curr->next; // Node 1003',
            cCodeSnippet: 'newNode->next = curr->next;',
          },
          {
            stepId: 'l2-t3-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link New Node PREV to Predecessor (Node 1001)',
            prompt: 'newNode->prev = 1001',
            instruction: "Click 'PREV' on Node 1002 and select Node 1001 to link backward to the predecessor.",
            target_field: 'newNode->prev',
            c_cpp_code: 'newNode->prev = curr; // Node 1001',
            cCodeSnippet: 'newNode->prev = curr;',
          },
          {
            stepId: 'l2-t3-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link Successor PREV backward to New Node',
            prompt: '1003.prev = 1002',
            instruction: "Click 'PREV' on Node 1003 and select Node 1002 to rewire the successor's backward link.",
            target_field: 'curr->next->prev',
            c_cpp_code: 'curr->next->prev = newNode; // 1003.prev = 1002',
            cCodeSnippet: 'curr->next->prev = newNode;',
          },
          {
            stepId: 'l2-t3-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Link Predecessor NEXT forward to New Node',
            prompt: '1001.next = 1002',
            instruction: "Click 'NEXT' on Node 1001 and select Node 1002 to complete the middle insertion.",
            target_field: 'curr->next',
            c_cpp_code: 'curr->next = newNode; // 1001.next = 1002',
            cCodeSnippet: 'curr->next = newNode;',
          },
        ],
        initialHeapNodes: [
          { address: 1001, data: 10, prev: null, next: 1003 },
          { address: 1003, data: 30, prev: 1001, next: null },
        ],
        initialHeadAddress: 1001,
        initialTailAddress: 1003,
        newNodeToAllocate: { address: 1002, data: 20 },
        expectedFinalAddresses: [1001, 1002, 1003],
        expectedFinalHeadAddress: 1001,
        expectedFinalTailAddress: 1003,
        atomicSteps: [
          {
            id: 'l2-t3-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Allocate Memory for Intermediate Node',
            label: 'Allocate Node 1002',
            instruction: "Click '+ Allocate Node [20]' in Pointer Tools.",
            description: 'Allocate memory block on the heap.',
            action_type: 'CLICK_ALLOCATE',
            actionType: 'create_node',
            target_field: 'newNode',
            targetAddress: 1002,
            c_cpp_code: 'Node* newNode = (Node*)malloc(sizeof(Node));',
            cCodeSnippet: 'Node* newNode = (Node*)malloc(sizeof(Node));',
          },
          {
            id: 'l2-t3-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Set Node Data Value',
            label: 'newNode->data = 20',
            instruction: "Set Node 1002 data payload to 20.",
            description: 'Store integer data in payload.',
            action_type: 'SET_VALUE',
            actionType: 'set_data',
            target_field: 'newNode->data',
            targetAddress: 1002,
            targetValue: 20,
            c_cpp_code: 'newNode->data = 20;',
            cCodeSnippet: 'newNode->data = 20;',
          },
          {
            id: 'l2-t3-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Link New Node NEXT to Successor (1003)',
            label: '1002.next = 1003',
            instruction: "Set Node 1002 NEXT pointer to Node 1003.",
            description: 'Link new node forward to successor.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'newNode->next',
            fromAddress: 1002,
            targetAddress: 1003,
            c_cpp_code: 'newNode->next = curr->next;',
            cCodeSnippet: 'newNode->next = curr->next;',
          },
          {
            id: 'l2-t3-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Link New Node PREV to Predecessor (1001)',
            label: '1002.prev = 1001',
            instruction: "Set Node 1002 PREV pointer to Node 1001.",
            description: 'Link new node backward to predecessor.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'newNode->prev',
            fromAddress: 1002,
            targetAddress: 1001,
            c_cpp_code: 'newNode->prev = curr;',
            cCodeSnippet: 'newNode->prev = curr;',
          },
          {
            id: 'l2-t3-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Link Successor PREV backward to New Node',
            label: '1003.prev = 1002',
            instruction: "Set Node 1003 PREV pointer to Node 1002.",
            description: 'Rewire successor backward pointer.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'curr->next->prev',
            fromAddress: 1003,
            targetAddress: 1002,
            c_cpp_code: 'curr->next->prev = newNode;',
            cCodeSnippet: 'curr->next->prev = newNode;',
          },
          {
            id: 'l2-t3-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Link Predecessor NEXT forward to New Node',
            label: '1001.next = 1002',
            instruction: "Set Node 1001 NEXT pointer to Node 1002.",
            description: 'Rewire predecessor forward pointer to complete middle insertion.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'curr->next',
            fromAddress: 1001,
            targetAddress: 1002,
            c_cpp_code: 'curr->next = newNode;',
            cCodeSnippet: 'curr->next = newNode;',
          },
        ],
      },
    ],
  },

  // =========================================================================
  // LEVEL 3: DELETION
  // =========================================================================
  {
    id: 3,
    title: 'LEVEL 3 — Deletion',
    subtitle: 'Free memory safely from beginning, end, and middle',
    operation: 'Deletion',
    badge: 'Memory Safety & free() Operations',
    description: 'Master clean node detachment without memory leaks: isolate pointers, advance boundary registers, call free() on dynamic heap memory, and prevent dangling pointers.',
    tasks: [
      // -----------------------------------------------------------------------
      // TASK 1: DELETE AT BEGINNING
      // -----------------------------------------------------------------------
      {
        id: 'L3-T1',
        task_id: 1,
        taskNumber: 1,
        title: 'Delete at Beginning',
        task_title: 'Delete at Beginning',
        summary: 'Store old HEAD in a temporary pointer, advance HEAD to the second node, sever boundary links, and deallocate memory with free(temp).',
        total_steps: 6,
        difficulty: '⭐⭐⭐',
        actionType: 'deletion',
        initialNodes: [10, 20, 30],
        initialHead: 10,
        expectedFinalNodes: [20, 30],
        finalHead: 20,
        targetDeleteValue: 10,
        hint: 'To delete from head: 1) temp = head, 2) head = head->next, 3) head->prev = NULL, 4) temp->next = NULL, 5) free(temp), and 6) temp = NULL.',
        successMessage: 'Well done! You safely detached and deallocated the head node from RAM without leaving dangling pointers.',
        pointerUpdates: [
          { link: 'temp = head', description: 'Store reference to old head (Node 1001)' },
          { link: 'head = head->next', description: 'Advance HEAD to Node 1002' },
          { link: 'head->prev = NULL', description: 'New head terminates backward link' },
          { link: 'temp->next = NULL', description: 'Isolate detached old head' },
          { link: 'free(temp)', description: 'Release memory back to OS' },
          { link: 'temp = NULL', description: 'Clear dangling pointer' },
        ],
        steps: [
          {
            stepId: 'l3-t1-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Assign Temporary Pointer to Current HEAD',
            prompt: 'temp = head (Node 1001)',
            instruction: "Select Node 1001 to designate it for removal before list modification (Node* temp = head).",
            target_field: 'temp',
            c_cpp_code: 'Node* temp = head; // Node 1001',
            cCodeSnippet: 'Node* temp = head;',
          },
          {
            stepId: 'l3-t1-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Advance HEAD Register to Next Node',
            prompt: 'head = head->next (Node 1002)',
            instruction: "Click the 'HEAD' register and select Node 1002 to advance HEAD forward.",
            target_field: 'head',
            c_cpp_code: 'head = head->next; // Node 1002',
            cCodeSnippet: 'head = head->next;',
          },
          {
            stepId: 'l3-t1-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Sever New HEAD PREV Link',
            prompt: 'head->prev = NULL',
            instruction: "Click 'PREV' on Node 1002 and select 'NULL' to terminate the start of the list.",
            target_field: 'head->prev',
            c_cpp_code: 'head->prev = NULL;',
            cCodeSnippet: 'head->prev = NULL;',
          },
          {
            stepId: 'l3-t1-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Sever Detached Node NEXT Link',
            prompt: 'temp->next = NULL',
            instruction: "Click 'NEXT' on Node 1001 and select 'NULL' to isolate the node from the chain.",
            target_field: 'temp->next',
            c_cpp_code: 'temp->next = NULL;',
            cCodeSnippet: 'temp->next = NULL;',
          },
          {
            stepId: 'l3-t1-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'free_memory',
            action_type: 'FREE_MEMORY',
            title: 'Free Memory of Old Head Node',
            prompt: 'free(temp)',
            instruction: "Click 'Delete Node' with Node 1001 selected to deallocate its heap RAM block.",
            target_field: 'temp',
            c_cpp_code: 'free(temp);',
            cCodeSnippet: 'free(temp);',
          },
          {
            stepId: 'l3-t1-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Nullify Temporary Pointer',
            prompt: 'temp = NULL',
            instruction: "Set TEMP pointer to NULL to eliminate dangling memory reference.",
            target_field: 'temp',
            c_cpp_code: 'temp = NULL;',
            cCodeSnippet: 'temp = NULL;',
          },
        ],
        initialHeapNodes: [
          { address: 1001, data: 10, prev: null, next: 1002 },
          { address: 1002, data: 20, prev: 1001, next: 1003 },
          { address: 1003, data: 30, prev: 1002, next: null },
        ],
        initialHeadAddress: 1001,
        initialTailAddress: 1003,
        expectedFinalAddresses: [1002, 1003],
        expectedFinalHeadAddress: 1002,
        expectedFinalTailAddress: 1003,
        atomicSteps: [
          {
            id: 'l3-t1-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Assign TEMP to Current HEAD',
            label: 'temp = head (Node 1001)',
            instruction: "Point TEMP to Node 1001.",
            description: 'Save address of node to be deleted in temp pointer.',
            action_type: 'SET_POINTER',
            actionType: 'set_temp',
            target_field: 'temp',
            targetAddress: 1001,
            c_cpp_code: 'Node* temp = head;',
            cCodeSnippet: 'Node* temp = head;',
          },
          {
            id: 'l3-t1-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Advance HEAD to Next Node',
            label: 'HEAD = Node 1002',
            instruction: "Update HEAD register to point to Node 1002.",
            description: 'Move head pointer forward to the next node.',
            action_type: 'SET_POINTER',
            actionType: 'set_head',
            target_field: 'head',
            targetAddress: 1002,
            c_cpp_code: 'head = head->next;',
            cCodeSnippet: 'head = head->next;',
          },
          {
            id: 'l3-t1-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Sever New HEAD PREV Link',
            label: '1002.prev = NULL',
            instruction: "Set Node 1002 PREV pointer to NULL.",
            description: 'Ensure new head has no predecessor link.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'head->prev',
            fromAddress: 1002,
            targetAddress: null,
            c_cpp_code: 'head->prev = NULL;',
            cCodeSnippet: 'head->prev = NULL;',
          },
          {
            id: 'l3-t1-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Sever Detached Node NEXT Link',
            label: '1001.next = NULL',
            instruction: "Set Node 1001 NEXT pointer to NULL.",
            description: 'Disconnect detached node from the rest of the list.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'temp->next',
            fromAddress: 1001,
            targetAddress: null,
            c_cpp_code: 'temp->next = NULL;',
            cCodeSnippet: 'temp->next = NULL;',
          },
          {
            id: 'l3-t1-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Free Memory of Old Head Node',
            label: 'free(temp) (Node 1001)',
            instruction: "Select Node 1001 and click 'Delete Node' to deallocate.",
            description: 'Deallocate memory of the detached node.',
            action_type: 'FREE_MEMORY',
            actionType: 'delete_node',
            target_field: 'temp',
            targetAddress: 1001,
            c_cpp_code: 'free(temp);',
            cCodeSnippet: 'free(temp);',
          },
          {
            id: 'l3-t1-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Nullify Temporary Pointer',
            label: 'temp = NULL',
            instruction: "Set TEMP pointer to NULL.",
            description: 'Clear dangling pointer reference.',
            action_type: 'SET_POINTER',
            actionType: 'set_temp',
            target_field: 'temp',
            targetAddress: null,
            c_cpp_code: 'temp = NULL;',
            cCodeSnippet: 'temp = NULL;',
          },
        ],
      },

      // -----------------------------------------------------------------------
      // TASK 2: DELETE AT END
      // -----------------------------------------------------------------------
      {
        id: 'L3-T2',
        task_id: 2,
        taskNumber: 2,
        title: 'Delete at End',
        task_title: 'Delete at End',
        summary: 'Track the old TAIL with a temporary pointer, retreat the TAIL register to the preceding node, sever links, and free memory.',
        total_steps: 6,
        difficulty: '⭐⭐⭐',
        actionType: 'deletion',
        initialNodes: [10, 20, 30],
        initialHead: 10,
        expectedFinalNodes: [10, 20],
        finalHead: 10,
        targetDeleteValue: 30,
        hint: 'To delete from tail: 1) temp = tail, 2) tail = tail->prev, 3) tail->next = NULL, 4) temp->prev = NULL, 5) free(temp), and 6) temp = NULL.',
        successMessage: 'Great work! You deleted the tail node in O(1) time and reclaimed heap RAM cleanly.',
        pointerUpdates: [
          { link: 'temp = tail', description: 'Store reference to old tail (Node 1003)' },
          { link: 'tail = tail->prev', description: 'Retreat TAIL to Node 1002' },
          { link: 'tail->next = NULL', description: 'New tail terminates forward link' },
          { link: 'temp->prev = NULL', description: 'Isolate detached old tail' },
          { link: 'free(temp)', description: 'Release memory back to OS' },
          { link: 'temp = NULL', description: 'Clear dangling pointer' },
        ],
        steps: [
          {
            stepId: 'l3-t2-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Assign Temporary Pointer to Current TAIL',
            prompt: 'temp = tail (Node 1003)',
            instruction: "Select Node 1003 to designate it for removal (Node* temp = tail).",
            target_field: 'temp',
            c_cpp_code: 'Node* temp = tail; // Node 1003',
            cCodeSnippet: 'Node* temp = tail;',
          },
          {
            stepId: 'l3-t2-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Retreat TAIL Register to Previous Node',
            prompt: 'tail = tail->prev (Node 1002)',
            instruction: "Click the 'TAIL' register and select Node 1002 to retreat TAIL to the preceding node.",
            target_field: 'tail',
            c_cpp_code: 'tail = tail->prev; // Node 1002',
            cCodeSnippet: 'tail = tail->prev;',
          },
          {
            stepId: 'l3-t2-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Sever New TAIL NEXT Link',
            prompt: 'tail->next = NULL',
            instruction: "Click 'NEXT' on Node 1002 and select 'NULL' to terminate the list forward.",
            target_field: 'tail->next',
            c_cpp_code: 'tail->next = NULL;',
            cCodeSnippet: 'tail->next = NULL;',
          },
          {
            stepId: 'l3-t2-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Sever Detached Node PREV Link',
            prompt: 'temp->prev = NULL',
            instruction: "Click 'PREV' on Node 1003 and select 'NULL' to disconnect backward reference.",
            target_field: 'temp->prev',
            c_cpp_code: 'temp->prev = NULL;',
            cCodeSnippet: 'temp->prev = NULL;',
          },
          {
            stepId: 'l3-t2-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'free_memory',
            action_type: 'FREE_MEMORY',
            title: 'Free Memory of Old Tail Node',
            prompt: 'free(temp)',
            instruction: "Click 'Delete Node' with Node 1003 selected to deallocate its heap RAM block.",
            target_field: 'temp',
            c_cpp_code: 'free(temp);',
            cCodeSnippet: 'free(temp);',
          },
          {
            stepId: 'l3-t2-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Nullify Temporary Pointer',
            prompt: 'temp = NULL',
            instruction: "Set TEMP pointer to NULL to avoid a dangling pointer reference.",
            target_field: 'temp',
            c_cpp_code: 'temp = NULL;',
            cCodeSnippet: 'temp = NULL;',
          },
        ],
        initialHeapNodes: [
          { address: 1001, data: 10, prev: null, next: 1002 },
          { address: 1002, data: 20, prev: 1001, next: 1003 },
          { address: 1003, data: 30, prev: 1002, next: null },
        ],
        initialHeadAddress: 1001,
        initialTailAddress: 1003,
        expectedFinalAddresses: [1001, 1002],
        expectedFinalHeadAddress: 1001,
        expectedFinalTailAddress: 1002,
        atomicSteps: [
          {
            id: 'l3-t2-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Assign TEMP to Current TAIL',
            label: 'temp = tail (Node 1003)',
            instruction: "Point TEMP to Node 1003.",
            description: 'Save address of tail node to delete.',
            action_type: 'SET_POINTER',
            actionType: 'set_temp',
            target_field: 'temp',
            targetAddress: 1003,
            c_cpp_code: 'Node* temp = tail;',
            cCodeSnippet: 'Node* temp = tail;',
          },
          {
            id: 'l3-t2-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Retreat TAIL to Previous Node',
            label: 'TAIL = Node 1002',
            instruction: "Update TAIL register to point to Node 1002.",
            description: 'Retreat tail pointer backward.',
            action_type: 'SET_POINTER',
            actionType: 'set_tail',
            target_field: 'tail',
            targetAddress: 1002,
            c_cpp_code: 'tail = tail->prev;',
            cCodeSnippet: 'tail = tail->prev;',
          },
          {
            id: 'l3-t2-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Sever New TAIL NEXT Link',
            label: '1002.next = NULL',
            instruction: "Set Node 1002 NEXT pointer to NULL.",
            description: 'Terminate forward list at new tail.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'tail->next',
            fromAddress: 1002,
            targetAddress: null,
            c_cpp_code: 'tail->next = NULL;',
            cCodeSnippet: 'tail->next = NULL;',
          },
          {
            id: 'l3-t2-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Sever Detached Node PREV Link',
            label: '1003.prev = NULL',
            instruction: "Set Node 1003 PREV pointer to NULL.",
            description: 'Disconnect detached node backwards.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'temp->prev',
            fromAddress: 1003,
            targetAddress: null,
            c_cpp_code: 'temp->prev = NULL;',
            cCodeSnippet: 'temp->prev = NULL;',
          },
          {
            id: 'l3-t2-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Free Memory of Old Tail Node',
            label: 'free(temp) (Node 1003)',
            instruction: "Select Node 1003 and click 'Delete Node' to deallocate.",
            description: 'Deallocate memory of the old tail node.',
            action_type: 'FREE_MEMORY',
            actionType: 'delete_node',
            target_field: 'temp',
            targetAddress: 1003,
            c_cpp_code: 'free(temp);',
            cCodeSnippet: 'free(temp);',
          },
          {
            id: 'l3-t2-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Nullify Temporary Pointer',
            label: 'temp = NULL',
            instruction: "Set TEMP pointer to NULL.",
            description: 'Clear dangling pointer reference.',
            action_type: 'SET_POINTER',
            actionType: 'set_temp',
            target_field: 'temp',
            targetAddress: null,
            c_cpp_code: 'temp = NULL;',
            cCodeSnippet: 'temp = NULL;',
          },
        ],
      },

      // -----------------------------------------------------------------------
      // TASK 3: DELETE AT ANY POSITION
      // -----------------------------------------------------------------------
      {
        id: 'L3-T3',
        task_id: 3,
        taskNumber: 3,
        title: 'Delete at Any Position',
        task_title: 'Delete an Intermediate Node',
        summary: 'Bypass an interior node in a Doubly Linked List by rewiring predecessor and successor pointers directly, isolating the target, and freeing heap memory.',
        total_steps: 6,
        difficulty: '⭐⭐⭐⭐',
        actionType: 'deletion',
        initialNodes: [10, 20, 30],
        initialHead: 10,
        expectedFinalNodes: [10, 30],
        finalHead: 10,
        targetDeleteValue: 20,
        hint: 'To delete intermediate Node 1002: 1) temp = curr, 2) temp->prev->next = temp->next (1001.next = 1003), 3) temp->next->prev = temp->prev (1003.prev = 1001), 4) temp->next = NULL, 5) temp->prev = NULL, and 6) free(temp) with temp = NULL.',
        successMessage: 'Outstanding! You bypassed and removed an intermediate node with complete pointer re-alignment and memory deallocation.',
        pointerUpdates: [
          { link: 'temp = curr', description: 'Store reference to intermediate Node 1002' },
          { link: '1001.next = 1003', description: 'Route predecessor directly to successor' },
          { link: '1003.prev = 1001', description: 'Route successor directly to predecessor' },
          { link: 'temp->next = NULL', description: 'Sever forward link of isolated node' },
          { link: 'temp->prev = NULL', description: 'Sever backward link of isolated node' },
          { link: 'free(temp)', description: 'Deallocate intermediate node from heap' },
        ],
        steps: [
          {
            stepId: 'l3-t3-s1',
            stepNumber: 1,
            step_number: 1,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Identify and Assign Target Node to TEMP',
            prompt: 'temp = curr (Node 1002)',
            instruction: "Select middle Node 1002 to designate it for removal (Node* temp = curr).",
            target_field: 'temp',
            c_cpp_code: 'Node* temp = curr; // Node 1002',
            cCodeSnippet: 'Node* temp = curr;',
          },
          {
            stepId: 'l3-t3-s2',
            stepNumber: 2,
            step_number: 2,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Route Predecessor NEXT Directly to Successor',
            prompt: '1001.next = 1003',
            instruction: "Click 'NEXT' on Node 1001 and select Node 1003 to bypass Node 1002 forward.",
            target_field: 'temp->prev->next',
            c_cpp_code: 'temp->prev->next = temp->next; // 1001.next = 1003',
            cCodeSnippet: 'temp->prev->next = temp->next;',
          },
          {
            stepId: 'l3-t3-s3',
            stepNumber: 3,
            step_number: 3,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Route Successor PREV Directly to Predecessor',
            prompt: '1003.prev = 1001',
            instruction: "Click 'PREV' on Node 1003 and select Node 1001 to bypass Node 1002 backward.",
            target_field: 'temp->next->prev',
            c_cpp_code: 'temp->next->prev = temp->prev; // 1003.prev = 1001',
            cCodeSnippet: 'temp->next->prev = temp->prev;',
          },
          {
            stepId: 'l3-t3-s4',
            stepNumber: 4,
            step_number: 4,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Sever Isolated Node NEXT Pointer',
            prompt: 'temp->next = NULL',
            instruction: "Click 'NEXT' on Node 1002 and select 'NULL' to disconnect forward reference.",
            target_field: 'temp->next',
            c_cpp_code: 'temp->next = NULL;',
            cCodeSnippet: 'temp->next = NULL;',
          },
          {
            stepId: 'l3-t3-s5',
            stepNumber: 5,
            step_number: 5,
            totalStepsInTask: 6,
            type: 'set_pointer',
            action_type: 'SET_POINTER',
            title: 'Sever Isolated Node PREV Pointer',
            prompt: 'temp->prev = NULL',
            instruction: "Click 'PREV' on Node 1002 and select 'NULL' to disconnect backward reference.",
            target_field: 'temp->prev',
            c_cpp_code: 'temp->prev = NULL;',
            cCodeSnippet: 'temp->prev = NULL;',
          },
          {
            stepId: 'l3-t3-s6',
            stepNumber: 6,
            step_number: 6,
            totalStepsInTask: 6,
            type: 'free_memory',
            action_type: 'FREE_MEMORY',
            title: 'Free Memory of Intermediate Node',
            prompt: 'free(temp); temp = NULL;',
            instruction: "Click 'Delete Node' with Node 1002 selected to release heap RAM, then set temp = NULL.",
            target_field: 'temp',
            c_cpp_code: 'free(temp);\ntemp = NULL;',
            cCodeSnippet: 'free(temp);\ntemp = NULL;',
          },
        ],
        initialHeapNodes: [
          { address: 1001, data: 10, prev: null, next: 1002 },
          { address: 1002, data: 20, prev: 1001, next: 1003 },
          { address: 1003, data: 30, prev: 1002, next: null },
        ],
        initialHeadAddress: 1001,
        initialTailAddress: 1003,
        expectedFinalAddresses: [1001, 1003],
        expectedFinalHeadAddress: 1001,
        expectedFinalTailAddress: 1003,
        atomicSteps: [
          {
            id: 'l3-t3-atomic-1',
            stepNumber: 1,
            step_number: 1,
            title: 'Assign Target Node to TEMP',
            label: 'temp = curr (Node 1002)',
            instruction: "Point TEMP to intermediate Node 1002.",
            description: 'Designate node to be removed.',
            action_type: 'SET_POINTER',
            actionType: 'set_temp',
            target_field: 'temp',
            targetAddress: 1002,
            c_cpp_code: 'Node* temp = curr;',
            cCodeSnippet: 'Node* temp = curr;',
          },
          {
            id: 'l3-t3-atomic-2',
            stepNumber: 2,
            step_number: 2,
            title: 'Route Predecessor NEXT to Successor',
            label: '1001.next = 1003',
            instruction: "Set Node 1001 NEXT pointer directly to Node 1003.",
            description: 'Bypass Node 1002 forward.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'temp->prev->next',
            fromAddress: 1001,
            targetAddress: 1003,
            c_cpp_code: 'temp->prev->next = temp->next;',
            cCodeSnippet: 'temp->prev->next = temp->next;',
          },
          {
            id: 'l3-t3-atomic-3',
            stepNumber: 3,
            step_number: 3,
            title: 'Route Successor PREV to Predecessor',
            label: '1003.prev = 1001',
            instruction: "Set Node 1003 PREV pointer directly to Node 1001.",
            description: 'Bypass Node 1002 backward.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'temp->next->prev',
            fromAddress: 1003,
            targetAddress: 1001,
            c_cpp_code: 'temp->next->prev = temp->prev;',
            cCodeSnippet: 'temp->next->prev = temp->prev;',
          },
          {
            id: 'l3-t3-atomic-4',
            stepNumber: 4,
            step_number: 4,
            title: 'Sever Isolated Node NEXT Pointer',
            label: '1002.next = NULL',
            instruction: "Set Node 1002 NEXT pointer to NULL.",
            description: 'Isolate detached node forward.',
            action_type: 'SET_POINTER',
            actionType: 'set_next',
            target_field: 'temp->next',
            fromAddress: 1002,
            targetAddress: null,
            c_cpp_code: 'temp->next = NULL;',
            cCodeSnippet: 'temp->next = NULL;',
          },
          {
            id: 'l3-t3-atomic-5',
            stepNumber: 5,
            step_number: 5,
            title: 'Sever Isolated Node PREV Pointer',
            label: '1002.prev = NULL',
            instruction: "Set Node 1002 PREV pointer to NULL.",
            description: 'Isolate detached node backward.',
            action_type: 'SET_POINTER',
            actionType: 'set_prev',
            target_field: 'temp->prev',
            fromAddress: 1002,
            targetAddress: null,
            c_cpp_code: 'temp->prev = NULL;',
            cCodeSnippet: 'temp->prev = NULL;',
          },
          {
            id: 'l3-t3-atomic-6',
            stepNumber: 6,
            step_number: 6,
            title: 'Free Memory of Intermediate Node',
            label: 'free(temp); temp = NULL',
            instruction: "Select Node 1002 and click 'Delete Node' to deallocate.",
            description: 'Free memory block from RAM and clear dangling pointer.',
            action_type: 'FREE_MEMORY',
            actionType: 'delete_node',
            target_field: 'temp',
            targetAddress: 1002,
            c_cpp_code: 'free(temp);\ntemp = NULL;',
            cCodeSnippet: 'free(temp);\ntemp = NULL;',
          },
        ],
      },
    ],
  },
];
